Repository nf-core/sarek, pull requests merged in 2019-11, with the labels that each got.

#52 Mouse Genome Support
  CHANGELOG.md
  conf/genomes.config
  conf/igenomes.config
  docs/reference.md
  docs/usage.md
  main.nf
Labels: enhancement

#58 Fix issue with `wholegenome.interval_list` file
  CHANGELOG.md
  main.nf
Labels: bug

#69 add CODEOWNERS file
  .github/CODEOWNERS
Labels: docs
