Repository nf-core/sarek, pull requests merged in 2019-09, with the labels that each got.

#22 Memory parameter singleCPUMem is now possible to use
  CHANGELOG.md
  conf/base.config
Labels: bug

#27 Add GitHubActions
  .github/workflows/branch.yml
  .github/workflows/ci.yml
  .github/workflows/linting.yml
  .travis.yml
  CHANGELOG.md
  README.md
  scripts/build_reference.sh
  scripts/download_image.sh
  scripts/run_tests.sh
Labels: enhancement

#30 small refactoring
  .github/workflows/branch.yml
  bin/scrape_software_versions.py
  main.nf
Labels: bug, enhancement

#24 Panel of Normals
  CHANGELOG.md
  conf/genomes.config
  conf/igenomes.config
  docs/output.md
  docs/usage.md
  main.nf
Labels: enhancement, help wanted

#23 Change --sample by --input
  CHANGELOG.md
  build.nf
  conf/genomes.config
  conf/igenomes.config
  conf/test.config
  docs/input.md
  docs/usage.md
  docs/use_cases.md
  main.nf
  nextflow.config
  scripts/run_tests.sh
Labels: enhancement, question

#38 Avoid collision in MultiQC
  CHANGELOG.md
  main.nf
  nextflow.config
Labels: bug
