Repository nf-core/sarek, pull requests merged in 2020-07, with the labels that each got.

#234 Conversion to DSL2
  .github/workflows/ci.yml
  .vscode/settings.json
  CHANGELOG.md
  README.md
  conf/test.config
  lib/Checks.groovy
  lib/Completion.groovy
  lib/Headers.groovy
  lib/Schema.groovy
  main.nf
  modules/local/build_intervals.nf
  modules/local/buildindices.nf
  modules/local/functions.nf
  modules/local/gatk_dict.nf
  modules/local/get_software_versions.nf
  modules/local/mapreads.nf
  modules/local/output_documentation.nf
  modules/nf-core/bwamem2_index.nf
  modules/nf-core/fastqc.nf
  modules/nf-core/htslib_tabix.nf
  modules/nf-core/multiqc.nf
  modules/nf-core/samtools_faidx.nf
Labels: enhancement

#236 fixed Mutect2 typo #227
  CHANGELOG.md
  main.nf
Labels: bugfix

#242 Code polishing + add BWAMEM2_MEM process
  lib/Headers.groovy
  lib/Schema.groovy
  main.nf
  modules/local/build_intervals.nf
  modules/local/bwamem2_mem.nf
  modules/local/create_intervals_bed.nf
  modules/local/functions.nf
  modules/local/gatk_dict.nf
  modules/local/get_software_versions.nf
  modules/local/mapreads.nf
  modules/local/output_documentation.nf
  modules/local/trim_galore.nf
  modules/nf-core/bwamem2_index.nf
  modules/nf-core/bwamem2_mem.nf
  modules/nf-core/fastqc.nf
  modules/nf-core/htslib_tabix.nf
  modules/nf-core/multiqc.nf
  modules/nf-core/samtools_faidx.nf
  modules/subworkflows/build_indices.nf
Labels: DSL2

#145 Add UMI reads processing capability
  CHANGELOG.md
  conf/test_umi.config
  docs/usage.md
  environment.yml
  main.nf
Labels: enhancement
