Repository nf-core/sarek, pull requests merged in 2020-03, with the labels that each got.

#141 fix download cache script + further improvements
  .circleci/config.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  conf/genomes.config
  conf/igenomes.config
  conf/test_annotation.config
  download_cache.nf
  main.nf
Labels: bugfix, enhancement

#143 fix annotation tests
  .circleci/config.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  conf/genomes.config
  conf/igenomes.config
  conf/test_annotation.config
  main.nf
Labels: bugfix

#140 Fix issue #136: Ascat computes all possible N-T combinations
  main.nf
Labels: bugfix

#144 Fix CircleCI building of VEP containers
  .circleci/config.yml
  CHANGELOG.md
Labels: bugfix

#146 Fix issue #135: mutect2 fails with --no_intervals option
  .github/workflows/ci.yml
  bin/concatenateVCFs.sh
  main.nf
Labels: enhancement

#156 More fixes
  CHANGELOG.md
  main.nf
Labels: bugfix
