Repository nf-core/sarek, pull requests merged in 2020-02, with the labels that each got.

#109 Update Sarek publication
  CHANGELOG.md
  README.md
Labels: docs

#110 Fix snpEff report (issue with link to txt file)
  CHANGELOG.md
  docs/output.md
  main.nf
Labels: bugfix

#44 Improve ASCAT
  bin/convertAlleleCounts.r
  bin/run_ascat.r
  docs/ascat.md
  docs/install_bianca.md
  docs/usage.md
  main.nf
  nextflow.config
  scripts/ascat.R
Labels: enhancement

#67 Enable FilterMutect2Call without --pon
  .github/workflows/ci.yml
  docs/output.md
  main.nf
Labels: enhancement

#126 Fix typos
  conf/igenomes.config
  docs/input.md
Labels: bugfix, docs

#129 Fix bugs due to merging TEMPLATE Sync PR
  CHANGELOG.md
  bin/markdown_to_html.py
  conf/base.config
  docs/output.md
  docs/usage.md
  environment.yml
  main.nf
Labels: bugfix

#131 Prepare for 2.6 release
  CHANGELOG.md
  README.md
  containers/snpeff/Dockerfile
  containers/snpeff/environment.yml
  containers/vep/Dockerfile
  containers/vep/environment.yml
  docs/containers.md
  docs/usage.md
  downloadcache.nf
  environment.yml
  main.nf
  nextflow.config
Labels: release, update
