Repository nf-core/sarek, pull requests merged in 2020-04, with the labels that each got.

#176 fix custom genome possibility
  CHANGELOG.md
  conf/genomes.config
  conf/test_annotation.config
  docs/usage.md
Labels: enhancement

#180 improve minimal usage of Sarek
  CHANGELOG.md
  main.nf
Labels: enhancement

#188 fix input/output for IndexBamFile
  CHANGELOG.md
  main.nf
Labels: bugfix

#183 improve input.md
  CHANGELOG.md
  docs/input.md
Labels: docs

#189 fix no_intervals for HaplotypeCaller
  .github/workflows/ci.yml
  CHANGELOG.md
  main.nf
Labels: bugfix

#194 Update docs
  CHANGELOG.md
  docs/usage.md
Labels: docs

#178 Fix some Sentieon issues
  CHANGELOG.md
  main.nf
Labels: enhancement

#197 Updates on the minimal settings
  .github/markdownlint.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  containers/snpeff/Dockerfile
  containers/snpeff/environment.yml
  containers/vep/Dockerfile
  containers/vep/environment.yml
  docs/input.md
  docs/output.md
  docs/variant_calling.md
  main.nf
Labels: bugfix, enhancement
