Repository nf-core/sarek, pull requests merged in 2023-08, with the labels that each got.

#1177 Status inference update
  CHANGELOG.md
  assets/schema_input.json
  tests/csv/3.0/mapped_joint_bam.csv
Labels: Ready for Review

#1173 Fix GenomicsDB bug with mismatched intervals, remove duplicated variants from VQSR vcfs, add VQSR CI test
  CHANGELOG.md
  conf/modules/joint_germline.config
  conf/test/tools_germline.config
  modules.json
  modules/nf-core/gatk4/applyvqsr/main.nf
  modules/nf-core/gatk4/variantrecalibrator/main.nf
  subworkflows/local/bam_joint_calling_germline_gatk/main.nf
  subworkflows/local/bam_variant_calling_germline_all/main.nf
  subworkflows/local/bam_variant_calling_haplotypecaller/main.nf
  tests/test_joint_germline.yml
  workflows/sarek.nf
Labels: Ready for Review, samplesheet

#1171 fix getpileupsummary should not run if no germline resource is provided
  CHANGELOG.md
  conf/test.config
  conf/test/cache.config
  subworkflows/local/bam_variant_calling_somatic_mutect2/main.nf
  subworkflows/local/bam_variant_calling_tumor_only_mutect2/main.nf
  tests/test_tools_manually.yml
  workflows/sarek.nf
Labels: testing

#1202 ci: Remove Nextflow caching
  .github/workflows/ci.yml
  .github/workflows/pytest-workflow.yml
  .github/workflows/pytest-workflow_release.yml
  CHANGELOG.md
Labels: testing
